### ISSUE TITLE
Skipped links and content inside of parentheses

### ISSUE THREAD

**Issue by AppleT1ny** [chrisurf/obsidian-voice#3]
Everything that's inside of a link [[Note-Monday]] or is inside of parentheses is being skipped in TTS.
My study notes are structured with having links to other notes inside my vault and those get skipped, as well as everything that's inside parentheses.

**Comment by chrisurf** [comment]
> Everything that's inside of a link [[Note-Monday]] or is inside of parentheses is being skipped in TTS.
> 
> My study notes are structured with having links to other notes inside my vault and those get skipped, as well as everything that's inside parentheses.

@AppleT1ny I'm aware of this feature. This is on the roadmap and shall be added in one of the next releases.

**Comment by AppleT1ny** [comment]
Ahh, good to know that this issue is known already. Other than that, I really like how this plugin was implemented.
I know, it has nothing to do with this issue, but I would also really appreciate being able to increase/decrease playback speed. I do not know where to get insight about your roadmap, so i do not know whether this is planned :)

**Comment by chrisurf** [comment]
> Ahh, good to know that this issue is known already. Other than that, I really like how this plugin was implemented.
> 
> I know, it has nothing to do with this issue, but I would also really appreciate being able to increase/decrease playback speed. I do not know where to get insight about your roadmap, so i do not know whether this is planned :)

@AppleT1ny There is currently no public road. Hence, this is just my small hobby project. However, your feedback is valuable and I'll try to look into increase/decrease playback speed sometime in the future.

**Comment by chrisurf** [comment]
@AppleT1ny your initial request (eg. [[Note-Monday]]) should be fixed with release 0.0.13. You can update now.

**Comment by chrisurf** [comment]
> Ahh, good to know that this issue is known already. Other than that, I really like how this plugin was implemented. I know, it has nothing to do with this issue, but I would also really appreciate being able to increase/decrease playback speed. I do not know where to get insight about your roadmap, so i do not know whether this is planned :)

@AppleT1ny just letting you know, that playback speed has been added with the latest release [0.0.15](https://github.com/chrisurf/obsidian-voice/releases/tag/0.0.15).

**Comment by chrisurf** [comment]
@AppleT1ny please consider upgrading to release 1.3.0 because a lot of feature improvements
