### ISSUE TITLE
Unable to setup polly

### ISSUE THREAD

**Issue by Eusorph** [chrisurf/obsidian-voice#5]
Hello,

I was able to open the AWS account but unable to set up Polly. It is way too complicated. There needs to be a step by step guide for it.

**Comment by Eusorph** [comment]
Also, I want to use the standard voice, not the neural, which is too expensive.

**Comment by chrisurf** [comment]
> Hello,
> 
> I was able to open the AWS account but unable to set up Polly. It is way too complicated. There needs to be a step by step guide for it.

@Eusorph , FYI - there isn't any specific setup to Polly required. 
You will only need to set up an IAM user with the access key credentials. 
If you are new to AWS, you might want to get familiar in setting up the access key, here is a step by step [video](https://www.youtube.com/watch?v=MoFTaGJE65Q).

If you have created a new AWS account then pricing should not matter that much, hence the first 12 month Polly comes free.  They provide a very generous free tier that to be honest is very hard to exceed.

**Comment by Eusorph** [comment]
I still did something wrong and nothing works. The first guide was all over the place and this one still jumped some knowledge. I think I'll give up. I had previously used Polly through another app and I just add to creat a username and password, if a remember correctly. There needs to be a REAL ste by step guide. At this point I might even messed up the account in wasy I don't even know.

**Comment by chrisurf** [comment]
@Eusorph, don't you worry. There are plenty of online guides on this topic. Without detailed information on where you get stuck, it is inefficient to get you up and running quickly. 
I'd recommend to get familiar with AWS Identity and Access Management (IAM), How to create a IAM user and add the `AmazonPollyFullAccess` policy and create the Access keys for that IAM user. 
Here is a similar [issue #4](https://github.com/chrisurf/obsidian-voice/issues/4) I previously saw, where you can find step by step instructions that seamed helpful.
