### ISSUE TITLE
Not loading at all on iOS 15.8.2.

### ISSUE THREAD

**Issue by itoldusoandso** [chrisurf/obsidian-voice#7]
The plugin loading Okay on iOS 17.4.1 but not loading at all on iOS 15.8.2.

Can this be fixed? I know iOS 15.8.2 no longer supported by Apple, but I can't upgrade higher because this is the last supported iOS on my iPad mini 4.

It says "Failed to load plugin voice".

I imported synced the plugin and settings.

But even if I do a clean install, it doesn't load.

**Comment by chrisurf** [comment]
Thank you for reporting this issue. Unfortunately, we only support iOS versions that are currently supported by Apple. iOS 15.8.2 is no longer in scope.
