### ISSUE TITLE
Free Tier ending issue

### ISSUE THREAD

**Issue by d4rkj0y** [chrisurf/obsidian-voice#8]
I wonder if you can help. I've used your plugin on the Obsidian, but my AWS free tier has come to an end this October.
I have looked through the AWS Management Console website. I can see the AWS Polly service listed but I'm unsure of how to delete the service as I don't want to get charged I know that you don't work for AWS, but would you have any ideas on how to remove this service because I don't want to get charged for it or indeed how to restart a free tier? TIA

**Comment by chrisurf** [comment]
Hi! The service operates on pay-as-you-go, so charges only occur with usage. To avoid costs, ensure no resources or workflows are actively using AWS Polly. You don’t need to “delete” the service itself. AWS free tier doesn’t reset, but you can create a billing alert or contact AWS support for guidance.
